object Form2: TForm2
  Left = 0
  Top = 0
  Caption = 'Form2'
  ClientHeight = 613
  ClientWidth = 1103
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object cxScrollBox1: TcxScrollBox
    Left = 0
    Top = 0
    Width = 1103
    Height = 613
    Align = alClient
    AutoScroll = False
    HorzScrollBar.Range = 36
    TabOrder = 0
    VertScrollBar.Range = 1800
    object RzPanel1: TRzPanel
      Left = 33
      Top = 0
      Width = 1048
      Height = 1800
      Align = alClient
      BorderOuter = fsButtonDown
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #24494#36719#38597#40657
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object GrpListBox: TRzGroupBox
        Left = 2
        Top = 479
        Width = 1044
        Height = 178
        Align = alTop
        BannerHeight = 24
        BorderOuter = fsFlat
        Caption = #26131#24863#22240#32032
        CaptionFont.Charset = ANSI_CHARSET
        CaptionFont.Color = 7879740
        CaptionFont.Height = -19
        CaptionFont.Name = #24494#36719#38597#40657
        CaptionFont.Style = []
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 7879740
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        GroupStyle = gsBanner
        ParentColor = True
        ParentFont = False
        TabOrder = 0
        VisualStyle = vsClassic
        object pnl3: TPanel
          Left = 1
          Top = 25
          Width = 1042
          Height = 152
          Align = alClient
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          object lbl6: TLabel
            Left = 25
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #30149#20154'ID'#21495#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl7: TLabel
            Left = 25
            Top = 22
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #30149#20154#22995#21517#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl8: TLabel
            Left = 296
            Top = 22
            Width = 44
            Height = 16
            AutoSize = False
            Caption = #24615#21035#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl10: TLabel
            Left = 267
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl11: TLabel
            Left = 25
            Top = 80
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#35786#26029#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl12: TLabel
            Left = 717
            Top = 79
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20027#27835#21307#29983#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl13: TLabel
            Left = 496
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl14: TLabel
            Left = 25
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#31185#23460#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl15: TLabel
            Left = 267
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#21307#29983#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object btnBtnDept: TSpeedButton
            Left = 230
            Top = 106
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object btnBtnClinic: TSpeedButton
            Left = 456
            Top = 76
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object btnbgDoctor: TSpeedButton
            Left = 456
            Top = 106
            Width = 19
            Height = 20
            Caption = '...'
            Enabled = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
            Visible = False
          end
          object btnzgDoctor: TSpeedButton
            Left = 924
            Top = 76
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object lbl2: TLabel
            Left = 496
            Top = 80
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #26159#21542#28431#25253#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl16: TLabel
            Left = 717
            Top = 22
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20986#29983#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl17: TLabel
            Left = 717
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #31185#23460#30005#35805#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl18: TLabel
            Left = 717
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#31185#23460#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object bvl1: TBevel
            Left = 571
            Top = 97
            Width = 127
            Height = 1
            Style = bsRaised
          end
          object lbl19: TLabel
            Left = 496
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20986#38498#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl9: TLabel
            Left = 520
            Top = 22
            Width = 49
            Height = 16
            Alignment = taRightJustify
            AutoSize = False
            Caption = #24180#40836#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl1: TLabel
            Left = 731
            Top = 1
            Width = 57
            Height = 16
            AutoSize = False
            Caption = #30149#26696#21495#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object dbedtpatient_id: TDBEdit
            Left = 102
            Top = 48
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'patient_id'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
          end
          object dbedtname: TDBEdit
            Left = 102
            Top = 20
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
          end
          object dbedtage: TDBEdit
            Left = 571
            Top = 20
            Width = 127
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'age'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 3
          end
          object dbedtbase_diagnosis_desc: TDBEdit
            Left = 102
            Top = 77
            Width = 351
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            DataField = 'base_diagnosis_desc'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            TabOrder = 8
          end
          object dbedtdept_name: TDBEdit
            Left = 102
            Top = 106
            Width = 126
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'dept_name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 13
          end
          object dbedtdoctor: TDBEdit
            Left = 795
            Top = 77
            Width = 127
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'doctor'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 9
          end
          object dbedtoperator: TDBEdit
            Left = 346
            Top = 106
            Width = 107
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'operator'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 14
          end
          object cxdbdtdtReport_date: TcxDBDateEdit
            Left = 571
            Top = 104
            DataBinding.DataField = 'create_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 12
            Width = 127
          end
          object cxdbdtdtIn_date: TcxDBDateEdit
            Left = 346
            Top = 46
            DataBinding.DataField = 'admission_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 4
            Width = 132
          end
          object dbchkRpt: TDBCheckBox
            Left = 579
            Top = 78
            Width = 54
            Height = 17
            Caption = #28431#25253
            DataField = 'islb'
            Font.Charset = GB2312_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 10
            Visible = False
          end
          object cxdbdtdtBirth_date: TcxDBDateEdit
            Left = 795
            Top = 18
            DataBinding.DataField = 'birth_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.BorderStyle = ebsUltraFlat
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.ButtonTransparency = ebtNone
            Style.IsFontAssigned = True
            TabOrder = 1
            Width = 149
          end
          object dbedttelphone: TDBEdit
            Left = 795
            Top = 106
            Width = 149
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            DataField = 'telphone'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            TabOrder = 15
          end
          object dbedtname1: TDBEdit
            Left = 795
            Top = 48
            Width = 149
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'dept_name_in'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
          end
          object cxdbdtdtdischarge_date: TcxDBDateEdit
            Left = 571
            Top = 46
            DataBinding.DataField = 'discharge_date'
            ParentFont = False
            Properties.Kind = ckDateTime
            Properties.ReadOnly = False
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 5
            Width = 127
          end
          object dbcbbsex: TDBComboBox
            Left = 346
            Top = 18
            Width = 131
            Height = 23
            Style = csDropDownList
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            Color = clCream
            DataField = 'sex'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            Items.Strings = (
              #30007
              #22899)
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
          end
          object dbchkislate: TDBCheckBox
            Left = 643
            Top = 78
            Width = 54
            Height = 17
            Caption = #36831#25253
            DataField = 'IsLate'
            Font.Charset = GB2312_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 11
            Visible = False
          end
          object dbedtFInpNO: TDBEdit
            Left = 797
            Top = -2
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'FInpNO'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 16
          end
        end
      end
      object RzGroupBox2: TRzGroupBox
        Left = 2
        Top = 62
        Width = 1044
        Height = 239
        Align = alTop
        BannerHeight = 24
        BorderOuter = fsFlat
        Caption = #24863#26579#22522#26412#20449#24687
        CaptionFont.Charset = ANSI_CHARSET
        CaptionFont.Color = 7879740
        CaptionFont.Height = -16
        CaptionFont.Name = #24494#36719#38597#40657
        CaptionFont.Style = []
        Font.Charset = ANSI_CHARSET
        Font.Color = 7879740
        Font.Height = -19
        Font.Name = #24494#36719#38597#40657
        Font.Style = []
        GroupStyle = gsBanner
        ParentColor = True
        ParentFont = False
        TabOrder = 1
        VisualStyle = vsClassic
        object pnl2: TPanel
          Left = 1
          Top = 25
          Width = 1042
          Height = 213
          Align = alClient
          BevelOuter = bvNone
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = 7879740
          Font.Height = -12
          Font.Name = #24494#36719#38597#40657
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object lbl33: TLabel
            Left = 750
            Top = 9
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #21345#29255#29366#24577#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl34: TLabel
            Left = 25
            Top = 9
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #20303'  '#38498' '#21495#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl35: TLabel
            Left = 269
            Top = 46
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #24615'      '#21035#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl36: TLabel
            Left = 25
            Top = 80
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #20837#38498#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl37: TLabel
            Left = 269
            Top = 80
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #20837#38498#35786#26029#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl38: TLabel
            Left = 750
            Top = 46
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #20027#27835#21307#29983#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl46: TLabel
            Left = 25
            Top = 182
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #20986#38498#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl47: TLabel
            Left = 496
            Top = 46
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #24180'      '#40836#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl43: TLabel
            Left = 25
            Top = 46
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #30149#20154#22995#21517#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl40: TLabel
            Left = 496
            Top = 148
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25253#21578#31185#23460#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl41: TLabel
            Left = 267
            Top = 149
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25253#21578#21307#29983#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl39: TLabel
            Left = 27
            Top = 148
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25253#21578#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl44: TLabel
            Left = 750
            Top = 148
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #31185#23460#30005#35805#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl42: TLabel
            Left = 25
            Top = 114
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #24863#26579#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl48: TLabel
            Left = 269
            Top = 114
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #24863#26579#31185#23460#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl49: TLabel
            Left = 496
            Top = 114
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #24863#26579#35786#26029#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl50: TLabel
            Left = 750
            Top = 114
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #24863#26579#37096#20301#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl52: TLabel
            Left = 269
            Top = 9
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #30149' '#20154'  ID'#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl53: TLabel
            Left = 270
            Top = 182
            Width = 75
            Height = 21
            AutoSize = False
            Caption = #36716#24402#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl54: TLabel
            Left = 496
            Top = 182
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #36716#24402#24773#20917#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl55: TLabel
            Left = 496
            Top = 9
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #20303#38498#27425#25968#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object edtPatName: TRzDBEdit
            Left = 102
            Top = 41
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'PATIENT_NAME'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 0
          end
          object edtPatUseCode: TRzDBEdit
            Left = 102
            Top = 7
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'PATIENT_USED_CODE'
            TabOrder = 1
            TextHint = #35831#36755#20837#20303#38498#21495#25353#22238#36710
            OnKeyPress = edtPatUseCodeKeyPress
          end
          object edtPatientID: TRzDBEdit
            Left = 346
            Top = 7
            Width = 138
            Height = 25
            DataSource = dsInfect
            DataField = 'PATIENT_ID'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 2
          end
          object edtSex: TRzDBEdit
            Left = 346
            Top = 41
            Width = 138
            Height = 25
            DataSource = dsInfect
            DataField = 'SEX'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 3
          end
          object edtVisitID: TRzDBEdit
            Left = 570
            Top = 7
            Width = 168
            Height = 25
            DataSource = dsInfect
            DataField = 'VISIT_ID'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 4
          end
          object edtAge: TRzDBEdit
            Left = 570
            Top = 41
            Width = 168
            Height = 25
            DataSource = dsInfect
            DataField = 'AGE'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 5
          end
          object edtInChargeDoc: TRzDBEdit
            Left = 823
            Top = 41
            Width = 120
            Height = 25
            DataSource = dsInfect
            DataField = 'INCHARGE_DOCTOR'
            TabOrder = 6
          end
          object edtStatus: TRzDBEdit
            Left = 823
            Top = 7
            Width = 120
            Height = 25
            DataSource = dsInfect
            DataField = 'STATUS'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 7
          end
          object edtInDiag: TRzDBEdit
            Left = 346
            Top = 75
            Width = 597
            Height = 25
            DataSource = dsInfect
            DataField = 'DIAGNOSIS'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 8
          end
          object edtInfectPart: TRzDBEdit
            Left = 823
            Top = 109
            Width = 120
            Height = 25
            DataSource = dsInfect
            DataField = 'INFECT_PART'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 9
          end
          object edtTel: TRzDBEdit
            Left = 823
            Top = 143
            Width = 120
            Height = 25
            DataSource = dsInfect
            DataField = 'DEPT_TEL'
            TabOrder = 10
          end
          object RzDBButtonEdit1: TRzDBButtonEdit
            Left = 570
            Top = 143
            Width = 168
            Height = 25
            DataSource = dsInfect
            DataField = 'REPORT_DEPT_NAME'
            TabOrder = 11
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object edtInfectDept: TRzDBButtonEdit
            Left = 348
            Top = 112
            Width = 138
            Height = 25
            DataSource = dsInfect
            DataField = 'INFECT_DEPT_NAME'
            TabOrder = 12
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object edtReportDoc: TRzDBButtonEdit
            Left = 346
            Top = 142
            Width = 138
            Height = 25
            DataSource = dsInfect
            DataField = 'REPORTER'
            TabOrder = 13
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object edtInfectDiag: TRzDBButtonEdit
            Left = 570
            Top = 109
            Width = 168
            Height = 25
            DataSource = dsInfect
            DataField = 'INFECT_DIAGNOSIS'
            TabOrder = 14
            AltBtnWidth = 15
            ButtonWidth = 15
            OnButtonClick = edtInfectDiagButtonClick
          end
          object edtRurnoverSituation: TRzDBButtonEdit
            Left = 570
            Top = 177
            Width = 168
            Height = 25
            DataSource = dsInfect
            DataField = 'RURNOVER_SITUATION'
            TabOrder = 15
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object dtpInDate: TRzDBDateTimeEdit
            Left = 102
            Top = 75
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'IN_DATE'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 16
            EditType = etDate
          end
          object dtpInfectDate: TRzDBDateTimeEdit
            Left = 102
            Top = 109
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'INFECT_DATE'
            TabOrder = 17
            EditType = etDate
          end
          object dtpReportDate: TRzDBDateTimeEdit
            Left = 102
            Top = 143
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'REPORT_DATE'
            TabOrder = 18
            EditType = etDate
          end
          object dtpOutDate: TRzDBDateTimeEdit
            Left = 102
            Top = 177
            Width = 150
            Height = 25
            DataSource = dsInfect
            DataField = 'OUT_DATE'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 19
            EditType = etDate
          end
          object dtpRurnoverDate: TRzDBDateTimeEdit
            Left = 346
            Top = 177
            Width = 138
            Height = 25
            DataSource = dsInfect
            DataField = 'RURNOVER_DATE'
            TabOrder = 20
            EditType = etDate
          end
          object RzDBCheckBox1: TRzDBCheckBox
            Left = 758
            Top = 175
            Width = 43
            Height = 19
            DataSource = dsInfect
            ValueChecked = 'True'
            ValueUnchecked = 'False'
            AlignmentVertical = avCenter
            Caption = #28431#25253
            TabOrder = 21
            Transparent = True
          end
          object RzDBCheckBox2: TRzDBCheckBox
            Left = 846
            Top = 175
            Width = 103
            Height = 19
            ValueChecked = 'True'
            ValueUnchecked = 'False'
            AlignmentVertical = avCenter
            Caption = #22810#37325#32784#33647#33740#24863#26579
            TabOrder = 22
            Transparent = True
          end
        end
      end
      object RzGroupBox3: TRzGroupBox
        Left = 2
        Top = 301
        Width = 1044
        Height = 178
        Align = alTop
        BannerHeight = 24
        BorderOuter = fsFlat
        Caption = #25163#26415#20449#24687
        CaptionFont.Charset = ANSI_CHARSET
        CaptionFont.Color = 7879740
        CaptionFont.Height = -19
        CaptionFont.Name = #24494#36719#38597#40657
        CaptionFont.Style = []
        Font.Charset = ANSI_CHARSET
        Font.Color = 7879740
        Font.Height = -19
        Font.Name = #24494#36719#38597#40657
        Font.Style = []
        GradientDirection = gdVerticalEnd
        GroupStyle = gsBanner
        ParentColor = True
        ParentFont = False
        TabOrder = 2
        VisualStyle = vsClassic
        object pnl4: TPanel
          Left = 1
          Top = 25
          Width = 1042
          Height = 152
          Align = alClient
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          object lbl3: TLabel
            Left = 728
            Top = 11
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25163#26415#26085#26399#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl4: TLabel
            Left = 22
            Top = 8
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25163#26415#21517#31216#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl5: TLabel
            Left = 25
            Top = 38
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25163#26415#21307#29983#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl20: TLabel
            Left = 276
            Top = 38
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #20999#21475#31561#32423#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl21: TLabel
            Left = 258
            Top = 71
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25253#21578#21307#29983#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl22: TLabel
            Left = 500
            Top = 100
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25253#21578#21307#29983#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object lbl23: TLabel
            Left = 505
            Top = 38
            Width = 73
            Height = 21
            AutoSize = False
            Caption = #25163#26415#25345#32493#26102#38388#65306
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -16
            Font.Name = #24494#36719#38597#40657
            Font.Style = []
            ParentFont = False
          end
          object RzDBDateTimeEdit1: TRzDBDateTimeEdit
            Left = 803
            Top = 7
            Width = 150
            Height = 33
            DataSource = dsInfect
            DataField = 'REPORT_DATE'
            TabOrder = 0
            EditType = etDate
          end
          object RzDBEdit1: TRzDBEdit
            Left = 101
            Top = 3
            Width = 597
            Height = 33
            DataSource = dsInfect
            DataField = 'DIAGNOSIS'
            ReadOnly = True
            Color = clInfoBk
            TabOrder = 1
          end
          object RzDBButtonEdit2: TRzDBButtonEdit
            Left = 101
            Top = 34
            Width = 138
            Height = 33
            DataSource = dsInfect
            DataField = 'REPORTER'
            TabOrder = 2
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object RzDBButtonEdit4: TRzDBButtonEdit
            Left = 356
            Top = 73
            Width = 138
            Height = 33
            DataSource = dsInfect
            DataField = 'REPORTER'
            TabOrder = 3
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object RzDBButtonEdit5: TRzDBButtonEdit
            Left = 579
            Top = 96
            Width = 138
            Height = 33
            DataSource = dsInfect
            DataField = 'REPORTER'
            TabOrder = 4
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object RzDBButtonEdit6: TRzDBButtonEdit
            Left = 584
            Top = 34
            Width = 138
            Height = 33
            DataSource = dsInfect
            DataField = 'REPORTER'
            TabOrder = 5
            AltBtnWidth = 15
            ButtonWidth = 15
          end
          object RzDBComboBox1: TRzDBComboBox
            Left = 355
            Top = 34
            Width = 145
            Height = 33
            TabOrder = 6
          end
          object dbcbb1: TDBComboBox
            Left = 356
            Top = 112
            Width = 145
            Height = 33
            TabOrder = 7
          end
          object cxDBComboBox1: TcxDBComboBox
            Left = 210
            Top = 114
            TabOrder = 8
            Width = 121
          end
          object RzComboBox1: TRzComboBox
            Left = 22
            Top = 73
            Width = 145
            Height = 33
            TabOrder = 9
          end
        end
      end
      object RzGroupBox4: TRzGroupBox
        Left = 2
        Top = 657
        Width = 1044
        Height = 178
        Align = alTop
        BannerHeight = 24
        BorderOuter = fsFlat
        Caption = #36865#26816#20449#24687
        CaptionFont.Charset = ANSI_CHARSET
        CaptionFont.Color = 7879740
        CaptionFont.Height = -19
        CaptionFont.Name = #24494#36719#38597#40657
        CaptionFont.Style = []
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 7879740
        Font.Height = -11
        Font.Name = 'Verdana'
        Font.Style = []
        GroupStyle = gsBanner
        ParentColor = True
        ParentFont = False
        TabOrder = 3
        VisualStyle = vsClassic
        object pnl5: TPanel
          Left = 1
          Top = 25
          Width = 1042
          Height = 152
          Align = alClient
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          object lbl65: TLabel
            Left = 25
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #30149#20154'ID'#21495#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl66: TLabel
            Left = 25
            Top = 22
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #30149#20154#22995#21517#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl67: TLabel
            Left = 296
            Top = 22
            Width = 44
            Height = 16
            AutoSize = False
            Caption = #24615#21035#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl68: TLabel
            Left = 267
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl69: TLabel
            Left = 25
            Top = 80
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#35786#26029#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl70: TLabel
            Left = 717
            Top = 79
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20027#27835#21307#29983#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl71: TLabel
            Left = 496
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl72: TLabel
            Left = 25
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#31185#23460#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl73: TLabel
            Left = 267
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #25253#21578#21307#29983#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object btn13: TSpeedButton
            Left = 230
            Top = 106
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object btn14: TSpeedButton
            Left = 456
            Top = 76
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object btn15: TSpeedButton
            Left = 456
            Top = 106
            Width = 19
            Height = 20
            Caption = '...'
            Enabled = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
            Visible = False
          end
          object btn16: TSpeedButton
            Left = 924
            Top = 76
            Width = 19
            Height = 20
            Caption = '...'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object lbl74: TLabel
            Left = 496
            Top = 80
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #26159#21542#28431#25253#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl75: TLabel
            Left = 717
            Top = 22
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20986#29983#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl76: TLabel
            Left = 717
            Top = 108
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #31185#23460#30005#35805#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl77: TLabel
            Left = 717
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20837#38498#31185#23460#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object bvl5: TBevel
            Left = 571
            Top = 97
            Width = 127
            Height = 1
            Style = bsRaised
          end
          object lbl78: TLabel
            Left = 496
            Top = 50
            Width = 73
            Height = 16
            AutoSize = False
            Caption = #20986#38498#26085#26399#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl79: TLabel
            Left = 520
            Top = 22
            Width = 49
            Height = 16
            Alignment = taRightJustify
            AutoSize = False
            Caption = #24180#40836#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object lbl80: TLabel
            Left = 731
            Top = 1
            Width = 57
            Height = 16
            AutoSize = False
            Caption = #30149#26696#21495#65306
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
          end
          object dbedtpatient_id4: TDBEdit
            Left = 102
            Top = 48
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'patient_id'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
          end
          object dbedtname5: TDBEdit
            Left = 102
            Top = 20
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
          end
          object dbedtage4: TDBEdit
            Left = 571
            Top = 20
            Width = 127
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'age'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 3
          end
          object dbedtbase_diagnosis_desc4: TDBEdit
            Left = 102
            Top = 77
            Width = 351
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            DataField = 'base_diagnosis_desc'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            TabOrder = 8
          end
          object dbedtdept_name4: TDBEdit
            Left = 102
            Top = 106
            Width = 126
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'dept_name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 13
          end
          object dbedtdoctor4: TDBEdit
            Left = 795
            Top = 77
            Width = 127
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'doctor'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 9
          end
          object dbedtoperator4: TDBEdit
            Left = 346
            Top = 106
            Width = 107
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'operator'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 14
          end
          object cxDBDateEdit13: TcxDBDateEdit
            Left = 571
            Top = 104
            DataBinding.DataField = 'create_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 12
            Width = 127
          end
          object cxDBDateEdit14: TcxDBDateEdit
            Left = 346
            Top = 46
            DataBinding.DataField = 'admission_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 4
            Width = 132
          end
          object dbchkislb3: TDBCheckBox
            Left = 579
            Top = 78
            Width = 54
            Height = 17
            Caption = #28431#25253
            DataField = 'islb'
            Font.Charset = GB2312_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 10
            Visible = False
          end
          object cxDBDateEdit15: TcxDBDateEdit
            Left = 795
            Top = 18
            DataBinding.DataField = 'birth_date'
            ParentFont = False
            Properties.ReadOnly = True
            Style.BorderStyle = ebsUltraFlat
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.ButtonTransparency = ebtNone
            Style.IsFontAssigned = True
            TabOrder = 1
            Width = 149
          end
          object dbedttelphone4: TDBEdit
            Left = 795
            Top = 106
            Width = 149
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            DataField = 'telphone'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            TabOrder = 15
          end
          object dbedtdept_name_in3: TDBEdit
            Left = 795
            Top = 48
            Width = 149
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'dept_name_in'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
          end
          object cxDBDateEdit16: TcxDBDateEdit
            Left = 571
            Top = 46
            DataBinding.DataField = 'discharge_date'
            ParentFont = False
            Properties.Kind = ckDateTime
            Properties.ReadOnly = False
            Style.Color = clCream
            Style.Edges = [bBottom]
            Style.Font.Charset = DEFAULT_CHARSET
            Style.Font.Color = clRed
            Style.Font.Height = -15
            Style.Font.Name = #23435#20307
            Style.Font.Style = []
            Style.IsFontAssigned = True
            TabOrder = 5
            Width = 127
          end
          object dbcbbsex4: TDBComboBox
            Left = 346
            Top = 18
            Width = 131
            Height = 23
            Style = csDropDownList
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            Color = clCream
            DataField = 'sex'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            Items.Strings = (
              #30007
              #22899)
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
          end
          object dbchkIsLate4: TDBCheckBox
            Left = 643
            Top = 78
            Width = 54
            Height = 17
            Caption = #36831#25253
            DataField = 'IsLate'
            Font.Charset = GB2312_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 11
            Visible = False
          end
          object dbedtFInpNO4: TDBEdit
            Left = 797
            Top = -2
            Width = 147
            Height = 21
            BevelEdges = [beBottom]
            BevelKind = bkFlat
            BorderStyle = bsNone
            Color = clCream
            DataField = 'FInpNO'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = []
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#25340#38899#36755#20837#27861
            ParentFont = False
            ReadOnly = True
            TabOrder = 16
          end
        end
      end
      object tbrMain: TRzToolbar
        Left = 2
        Top = 2
        Width = 1044
        Height = 60
        AutoStyle = False
        RowHeight = 44
        ButtonLayout = blGlyphTop
        ButtonWidth = 65
        ButtonHeight = 60
        ShowButtonCaptions = True
        TextOptions = ttoCustom
        WrapControls = False
        AutoSize = True
        BorderInner = fsNone
        BorderOuter = fsGroove
        BorderSides = []
        BorderWidth = 0
        GradientColorStop = 14215660
        TabOrder = 4
        VisualStyle = vsGradient
        ToolbarControls = (
          btnFrames
          btnEdits
          btnComboBoxes
          btnListBoxes
          btnCommon
          btnDisplay
          btnDatabase
          btnSendMsg)
        object btnFrames: TRzToolButton
          Left = 4
          Top = 0
          GroupIndex = 1
          HotIndex = 15
          Layout = blGlyphTop
          Caption = 'ICU'#30417#27979
          ParentShowHint = False
          ShowHint = True
        end
        object btnComboBoxes: TRzToolButton
          Left = 161
          Top = 0
          GroupIndex = 1
          HotIndex = 39
          Layout = blGlyphTop
          Caption = #32844#19994#26292#38706
          ParentShowHint = False
          ShowHint = True
        end
        object btnListBoxes: TRzToolButton
          Left = 226
          Top = 0
          GroupIndex = 1
          HotIndex = 35
          Layout = blGlyphTop
          Caption = #24863#26579#19978#25253
          ParentShowHint = False
          ShowHint = True
        end
        object btnCommon: TRzToolButton
          Left = 291
          Top = 0
          GroupIndex = 1
          HotIndex = 37
          Layout = blGlyphTop
          Caption = #29615#22659#21355#29983
          ParentShowHint = False
          ShowHint = True
        end
        object btnEdits: TRzToolButton
          Left = 69
          Top = 0
          Width = 92
          Height = 60
          GroupIndex = 1
          HotIndex = 31
          Layout = blGlyphTop
          Caption = #22810#37325#32784#33647#33740#30417#27979
          ParentShowHint = False
          ShowHint = True
        end
        object btnDatabase: TRzToolButton
          Left = 424
          Top = 0
          GroupIndex = 1
          HotIndex = 19
          Layout = blGlyphTop
          Caption = #19977#35777#31649#29702
          ParentShowHint = False
          ShowHint = True
        end
        object btnSendMsg: TRzToolButton
          Left = 489
          Top = 0
          GroupIndex = 1
          HotIndex = 43
          Layout = blGlyphTop
          Caption = #20020#24202#24178#39044
          ParentShowHint = False
          ShowHint = True
        end
        object btnDisplay: TRzToolButton
          Left = 356
          Top = 0
          Width = 68
          Height = 60
          GroupIndex = 1
          HotIndex = 3
          Layout = blGlyphTop
          Caption = #25239#29983#32032#31649#29702
          ParentShowHint = False
          ShowHint = True
        end
      end
    end
    object RzPanel3: TRzPanel
      Left = 0
      Top = 0
      Width = 33
      Height = 1800
      Align = alLeft
      BorderOuter = fsNone
      Color = cl3DLight
      TabOrder = 1
    end
    object RzPanel2: TRzPanel
      Left = 1081
      Top = 0
      Width = 3
      Height = 1800
      Align = alRight
      BorderOuter = fsNone
      Color = cl3DLight
      TabOrder = 2
    end
  end
  object qryInfect: TADOQuery
    Parameters = <>
    Left = 568
    Top = 160
  end
  object dsInfect: TDataSource
    DataSet = qryInfect
    Left = 628
    Top = 162
  end
  object qryTemp: TADOQuery
    Parameters = <>
    Left = 520
    Top = 160
  end
end
